Added new precip link for dates post 2023-07-02
UW-SASWE/RAT pull request #74
Opened 2023-08-23 22:51 UTC by SarathUW

2023-08-25 20:30 UTC, pritamd47 approved these changes
Thanks for making this update! Looks good for merging to me.

2023-09-08 08:19 UTC, SanchitMinocha commented on src/rat/data_processing/newdata.py
> +        if date >= datetime(2023, 7, 2):  # Version was changed from V06B to V06C
The date needs to be 1st July.

2023-09-08 08:22 UTC, SanchitMinocha commented on src/rat/data_processing/newdata.py
> +
Add above line 67, the link change for dates before 1 July 2023 (basically the same thing you did for IMERG Late). Also, put comment on both the additions (IMERG early and IMERG late) : "Version was changed from V06C to V06D".

2023-09-08 08:23 UTC, SanchitMinocha requested changes
Please add link change for IMERG early also and change the date to 1st July.

2023-09-13 00:34 UTC, SanchitMinocha commented
Included in #75

2023-09-13 00:34 UTC, closed without merging