ResORR plugin and minor fix for forecasting
UW-SASWE/RAT pull request #91
Opened 2024-02-19 22:42 UTC by SarathUW

Commit 1
    Fixed runtime issues with forecasting plugin
       -  rat fails if PLUGINS section is not present in config.
       -  removed unused import cfgrib statement
Commit 2
     Adding the ResORR plugin to RAT

2024-02-19 22:43 UTC, SanchitMinocha commented on src/rat/plugins/forecasting.py
Thanks for fixing it.

2024-02-19 22:59 UTC, SanchitMinocha commented on src/rat/plugins/resorr/runResorr.py
> +from tqdm.notebook import tqdm
This can be removed.

2024-02-19 23:03 UTC, SanchitMinocha requested changes
I have not read the ResORR code in detail. But it looks good, well-documented and error-handling  also seems great.

2024-02-20 03:20 UTC, SarathUW commented on src/rat/plugins/resorr/runResorr.py
> +from tqdm.notebook import tqdm
removed. Thanks for checking the code.

2024-02-20 03:54 UTC, SanchitMinocha approved these changes
Great work. Thank you for fixing it and pushing the plugin code.

2024-02-20 03:55 UTC, merged

2024-02-21 21:17 UTC, SanchitMinocha commented
Forgot to mention it earlier - @pritamd47 or @SarathUW 
Can anyone of you mention details of how to use ResORR from within RAT as a plugin in the [Plugins section of RAT docs](https://rat-satellitedams.readthedocs.io/en/latest/Plugins/Forecasting/). You can there mention for complete documentation on how ResORR works at [https://resorr.readthedocs.io/en/latest/](https://resorr.readthedocs.io/en/latest/).